#
# Copyright (C) 2019-2024 vdaas.org vald team <vald@vdaas.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: "Run release"
on:
  workflow_call:
    inputs:
      client_type:
        type: "string"
        description: "Set client type. e.g) go, python, node, java"
        required: false

# If a workflow is executed in duplicate, the first workflow continues to be executed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    if: startsWith( github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if tag is a LATEST.
        id: check_latest
        run: |
          TAG=$(echo "$GITHUB_REF" | sed -e 's:^refs/tags/::')  # e.g) v1.7.6
          LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1) # e.g) v1.7.6

          echo "IS_LATEST_RELEASE=$([ "${TAG}" = "${LATEST_TAG}" ] && echo true || echo false)" | tee -a $GITHUB_OUTPUT
          echo "TAG=${TAG}" | tee -a $GITHUB_OUTPUT
      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.check_latest.outputs.TAG }}
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
          make_latest: ${{ steps.check_latest.outputs.IS_LATEST_RELEASE }}

  publish-pypl:
    if: ${{ startsWith( github.ref, 'refs/tags/') && inputs.client_type == 'python'}}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vdaas/vald/vald-ci-container:nightly
      options: "--add-host host.docker.internal:host-gateway"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: vdaas/vald-client-ci/.github/actions/setup-language@main
        with:
          client_type: python
      - name: Install dependencies
        run: |
          make REPO=vdaas ci/deps/install
      - name: Prepare for publish
        run: |
          make REPO=vdaas ci/package/prepare
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PIP_USERNAME }}
          password: ${{ secrets.PIP_TOKEN }}

  publish-npm:
    if: ${{ startsWith( github.ref, 'refs/tags/') && inputs.client_type == 'node'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: vdaas/vald-client-ci/.github/actions/setup-language@main
        with:
          client_type: node
      - name: Prepare for publish
        run: |
          make REPO=vdaas ci/package/prepare
      - name: Publish
        run: |
          make REPO=vdaas ci/package/publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  publish-maven:
    if: ${{ startsWith( github.ref, 'refs/tags/') && inputs.client_type == 'java'}}
    runs-on: ubuntu-latest
    env:
      GPG_KEYID: ${{ secrets.GPG_KEYID }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: vdaas/vald-client-ci/.github/actions/setup-language@main
        with:
          client_type: java
      - name: Prepare for publish
        run: |
          make REPO=vdaas ci/package/prepare
      - name: Publish
        run: |
          make REPO=vdaas ci/package/publish
