name: Update Actions version
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  pull_request:
jobs:
  dump-contexts-to-log:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: vdaas/vald/.github/actions/dump-context@main

  update-version:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ secrets.CI_USER }}
      GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Run update command
        run: |
          make update/actions
      - name: Check difference
        id: check_diff
        run: |
          if git diff --quiet --exit-code; then
            echo "Nothing updated"
          else
            git diff && git status
            echo "HAS_GIT_DIFF=true" >> $GITHUB_OUTPUT
          fi
      - name: Create PR
        if: ${{ steps.check_diff.outputs.HAS_GIT_DIFF == 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          author: "vdaas-ci <vald@vdaas.org>"
          git-token: ${{ secrets.CI_TOKEN }}
          signoff: true
          delete-branch: true
          base: fix/test-branch
          title: "Update Actions dependency versions"
          body: "Automated pull request to update Actions."


      # - name: Create PR
      #   if: ${{ steps.check_diff.outputs.HAS_GIT_DIFF == 'true' }}
      #   run: |
      #     BASE_BRANCH_NAME=main
      #     UPDATED_BRANCH_NAME=fix/update-actions
      #
      #     PR_TITLE="Update Actions dependency versions"
      #     PR_BODY="Automated pull request to update Actions."
      #
      #     git add -A
      #     git checkout ${BASE_BRANCH_NAME}
      #     git checkout -b ${UPDATED_BRANCH_NAME} && git push origin ${UPDATED_BRANCH_NAME}
      #
      #     git commit -S --signoff -m ":robot: ${PR_TITLE}"
      #
      #     gh pr create --base ${BASE_BRANCH_NAME} \
      #                  --title "${PR_TITLE}" \
      #                  --body "${PR_BODY}"
          # git checkout ${BASE_BRANCH_NAME}
          # git checkout -b ${UPDATE_BRANCH_NAME} && git push origin ${UPDATE_BRANCH_NAME}
        # uses: peter-evans/create-pull-request@v6
        # with:
        #   base: main
        # run: |
        #   BASE_BRANCH_NAME=main
        #   UPDATE_BRANCH_NAME=fix/update-actions
        #
        #   git checkout ${BASE_BRANCH_NAME}
        #   git checkout -b ${UPDATE_BRANCH_NAME} && git push origin ${UPDATE_BRANCH_NAME}
      #
      #     gh pr create --base ${BASE_BRANCH_NAME} \
      #                  --title "Backport PR #${PR_NUM} to ${BRANCH_NAME} for ${PR_TITLE}" \
      #                  --body "${PR_BODY}"
      #
      #     echo "hello"
