name: Update Actions version
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  pull_request:
jobs:
  dump-contexts-to-log:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: vdaas/vald/.github/actions/dump-context@main

  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Run update command
        run: |
          make list/actions
          make update/actions
      - name: Check difference
        id: check_diff
        run: |
          if git diff --quiet --exit-code; then
            echo "Nothing updated"
          else
            git diff && git status && git add -A
            echo "HAS_GIT_DIFF=true" >> $GITHUB_OUTPUT
          fi
      - name: Create PR
        if: ${{ steps.check_diff.outputs.HAS_GIT_DIFF == 'true' }}
        run: |
          BASE_BRANCH_NAME=main
          UPDATE_BRANCH_NAME=fix/update-actions

          PR_BODY="test"

          gh pr create --base ${BASE_BRANCH_NAME} \
                       --title "Update Actions dependency versions" \
                       --body "${PR_BODY}"
          # git checkout ${BASE_BRANCH_NAME}
          # git checkout -b ${UPDATE_BRANCH_NAME} && git push origin ${UPDATE_BRANCH_NAME}
        # uses: peter-evans/create-pull-request@v6
        # with:
        #   base: main
        # run: |
        #   BASE_BRANCH_NAME=main
        #   UPDATE_BRANCH_NAME=fix/update-actions
        #
        #   git checkout ${BASE_BRANCH_NAME}
        #   git checkout -b ${UPDATE_BRANCH_NAME} && git push origin ${UPDATE_BRANCH_NAME}
      #
      #     gh pr create --base ${BASE_BRANCH_NAME} \
      #                  --title "Backport PR #${PR_NUM} to ${BRANCH_NAME} for ${PR_TITLE}" \
      #                  --body "${PR_BODY}"
      #
      #     echo "hello"
